# Generated by Django 3.0 on 2019-12-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('contact_details', models.TextField(blank=True, help_text='Contact details for the responsible(s) of the department.', verbose_name='contact details')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the process/process chain.', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Extended description of the process.', verbose_name='description')),
                ('applications', models.ManyToManyField(blank=True, help_text='Set of applications used to handle this process', related_name='processes', to='applications.Application')),
                ('department', models.ForeignKey(help_text='The department responsible for this process.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_processes', to='processes.Department', verbose_name='department')),
                ('initiating_processes', models.ManyToManyField(blank=True, help_text='The set of processes that may lead to this process being started.', related_name='initiates', to='processes.Process', verbose_name='initiating processes')),
                ('other_departments', models.ManyToManyField(blank=True, help_text='Other departments that may play a role in this process', related_name='involved_in', to='processes.Department', verbose_name='other departments')),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
            },
        ),
    ]
