# Generated by Django 3.0.1 on 2020-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='name',
            new_name='camunda_id'
        ),
    ]
