# Generated by Django 3.0.1 on 2020-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20200114_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(default='', help_text='Human-friendly name.', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
