# Generated by Django 3.0.1 on 2020-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0006_auto_20200116_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="deactivation_date",
            field=models.DateField(
                blank=True,
                help_text="Date when this process became deactivated/historical. Leave blank for 'in production' processes.",
                null=True,
                verbose_name="deactivation date",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="personal_data",
            field=models.BooleanField(
                default=True,
                help_text="Does personal data end up in the process?",
                verbose_name="personal data",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                    ("historical", "Historical"),
                ],
                default="active",
                max_length=50,
                verbose_name="process status",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[("high", "High risk"), ("low", "Low risk")],
                max_length=50,
                verbose_name="risk level",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="zaaktype",
            field=models.URLField(
                blank=True,
                help_text="Zaaktype in the Catalogi API.",
                max_length=1000,
                verbose_name="zaaktype",
            ),
        ),
    ]
