# Generated by Django 3.0.1 on 2020-02-24 13:09

from django.db import migrations

import django_activiti.fields


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0007_auto_20200120_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="activiti_id",
            field=django_activiti.fields.ProcessDefinitionField(
                blank=True,
                help_text="ID of the process definition in Activiti",
                max_length=64,
                verbose_name="Activiti process",
            ),
        ),
    ]
