# Generated by Django 3.0.1 on 2020-02-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0008_storage_storagelocation"),
        ("processes", "0008_process_activiti_id"),
    ]

    operations = []
