# Generated by Django 3.0.3 on 2020-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0010_auto_20200225_1353"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="depth",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="department",
            name="path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
