# Generated by Django 3.0.3 on 2020-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0012_fix_treebeard_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
