# Generated by Django 3.0.3 on 2020-02-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0013_auto_20200225_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="zaaktype_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The department owning the zaaktype.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="processes.Department",
                verbose_name="zaaktype owner",
            ),
        ),
    ]
