# Generated by Django 3.0 on 2019-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A description of the application - what does it do, when should you use it...', verbose_name='description')),
                ('url', models.URLField(blank=True, help_text='URL to the application - preferably a home page or similar.', verbose_name='url')),
                ('admin_url', models.URLField(blank=True, help_text='URL to the application administrative interface.', verbose_name='admin url')),
                ('vendor', models.CharField(help_text='Software vendor - who built the appliation and/or maintains it?', max_length=255, verbose_name='vendor')),
                ('repository_url', models.URLField(blank=True, help_text='URL to the code repository, e.g. Github, Gitlab, Bitbucket...', verbose_name='repository URL')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
    ]
