# Generated by Django 3.0 on 2019-12-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        help_text="The tier number of the layer", verbose_name="tier"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="a description of the layer - what is it aimed for... ",
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="layer",
            field=models.ForeignKey(
                default=0,
                help_text="The layer of the application.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="applications.Layer",
                verbose_name="layer",
            ),
            preserve_default=False,
        ),
    ]
