# Generated by Django 3.0.1 on 2020-01-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_camunda', '0002_camundaconfig_auth_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamundaBasicAuthConfig',
            fields=[
                ('camundaconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_camunda.CamundaConfig')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username for BasicAuth')),
                ('password', models.CharField(blank=True, max_length=150, verbose_name='password for BasicAuth')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_camunda.camundaconfig',),
        ),
    ]
